// import Head from 'next/head'
// const https = require('https');
// const agent = new https.Agent({
//   rejectUnauthorized: false
// });

// export async function getStaticProps({ params }){

//     const req = await fetch(`https://localhost:44953/weatherforecast`,
//     { agent,
//       method: 'GET',
//     })
//     const data = await req.json();
//     console.log(data)
//     return {
//         props: { api: data }
//     }
//   }



// export default function Backend({
//     api
//   }) {
//     console.log(api)
//     return (
//       <div>
//       <Head>
//           <title>Backend</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>
//         <div>
//         {api.map(api => (
//         <div>
//             <p>
//               {api.date}
//             </p>
//               <p>
//               {api.summary}
//             </p>
//               <p>
//               {api.temperatureC} degrees
//               </p>
//               </div>
//         ))}</div>
//       </div>
//     )
//   }
  
  