import Head from 'next/head'
import { useRouter } from 'next/router'
import Link from 'next/dist/client/link';
import CardFunction from '../../components/Card';
import style from '../../styles/Projects.module.css';
import { Grid } from '@mui/material';

export async function getStaticProps({ params }){

  const req = await fetch(`https://gist.githubusercontent.com/tordar/9a7120692cf9de1dc1ad0dc30e4a33ef/raw/54c618f19861fdc5a68bd8afa17765d5e4dedfc7/projects`)
  const data = await req.json();
  
  return {
      props: { projects: data }
  }
}



export default function Projects({ projects }) {


  return (
    <div>
    <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={5} justifyContent="space-evenly" alignItems="stretch">
      
        {projects.map(project => (
          
            <CardFunction
              key={project.id}
              title={project.header}
              info={project.info}
              github={project.github}
              link={project.link}
              html={project.html}
              css={project.css}
              bootstrap={project.bootstrap}
              javascript={project.javascript}
            />
        ))}
        </Grid>
    </div>
  )
}

