import Head from 'next/head'
import { useRouter } from 'next/router'
import Link from 'next/dist/client/link';
import Card from '../../components/Card';

export async function getStaticProps({ params }){

  const req = await fetch(`https://gist.githubusercontent.com/tordar/9a7120692cf9de1dc1ad0dc30e4a33ef/raw/ca0b6f845fa1931d3423a3b4901b44fe81fbf82a/projects`)
  const data = await req.json();
  
  return {
      props: { projects: data }
  }
}

export default function Projects({ projects }) {

  return (
    <div>
    <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {projects.map(project => (
            <Card
              key={project.id}
              title={project.header}
              info={project.info}
              github={project.github}
              link={project.link}
            />
        ))}
        </div>
    </div>
  )
}

