import Head from 'next/head'
import Tile from '../../components/Tile';

export async function getStaticProps({ params }){

  const req = await fetch(`https://gist.githubusercontent.com/tordar/bea1434715d28e0c043a6b8f4d6f5d34/raw/77374f8092e7be9f1e372c67f2831f8bf08ff2ac/skills`)
  const data = await req.json();
  
  return {
      props: { skills: data }
  }
}

export default function Skills({
  skills
}) {

  return (
    <div>
    <Head>
        <title>Skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="tileContainer">
      {/*{skills.map(skill => (*/}
            <Tile
              key={skills[0].id}
              // text={skill.header}
              info={skills[0].info}
              img={skills[0].img}
            /> 
        {/*))}*/}
        </div>
    </div>
  )
}

