import Head from 'next/head'
import Tile from '../../components/Tile';

export async function getStaticProps({ params }){

  const req = await fetch(`https://gist.githubusercontent.com/tordar/bea1434715d28e0c043a6b8f4d6f5d34/raw/19f57f85b6ab8fe468f9f62670b702896f468a0f/skills`)
  const data = await req.json();
  
  return {
      props: { skills: data }
  }
}

export default function Skills({
  skills
}) {

  return (
    <div>
    <Head>
        <title>Skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="tileContainer">
      {skills.map(skill => (
            <Tile
              key={skill.id}
              text={skill.header}
              info={skill.info}
            />
        ))}
        </div>
    </div>
  )
}

