import Head from 'next/head'
import { useRouter } from 'next/router'

export async function getStaticProps({ params }){

  const req = await fetch(`http://localhost:3000/projects.json`)
  const data = await req.json();
  
  return {
      props: { projects: data }
  }
}

export default function Projects({ projects }) {
    console.log(projects)

  return (
    <div>
    <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Here are some projects: </div>
      <div>
        {projects.header}
        </div>
        <div>
        {projects.info}
    </div>
    </div>
  )
}

